      MODULE AUTOSPC_SUMMARY_MSGS_USE_IFs

! USE Interface statements for all subroutines called by SUBROUTINE AUTOSPC_SUMMARY_MSGS
! No subrs CALL'd by SUBROUTINE AUTOSPC_SUMMARY_MSGS

      END MODULE AUTOSPC_SUMMARY_MSGS_USE_IFs
