      MODULE GET_FORMATTED_INTEGER_USE_IFs

! USE Interface statements for all subroutines called by SUBROUTINE GET_FORMATTED_INTEGER

      USE OURTIM_Interface

      END MODULE GET_FORMATTED_INTEGER_USE_IFs
