      MODULE PRINT_SP_ENVIRON_VARS_USE_IFs

! USE Interface statements for all subroutines called by SUBROUTINE PRINT_SP_ENVIRON_VARS
! No subrs CALL'd by SUBROUTINE PRINT_SP_ENVIRON_VARS

      END MODULE PRINT_SP_ENVIRON_VARS_USE_IFs
