      MODULE SET_SPARSE_MAT_SYM_USE_IFs

! USE Interface statements for all subroutines called by SUBROUTINE SET_SPARSE_MAT_SYM
! No subrs CALL'd by SUBROUTINE SET_SPARSE_MAT_SYM

      END MODULE SET_SPARSE_MAT_SYM_USE_IFs
