      MODULE WRITE_ALLOC_MEM_TABLE_USE_IFs

! USE Interface statements for all subroutines called by SUBROUTINE WRITE_ALLOC_MEM_TABLE
! No subrs CALL'd by SUBROUTINE WRITE_ALLOC_MEM_TABLE

      END MODULE WRITE_ALLOC_MEM_TABLE_USE_IFs
