      MODULE WRT_REAL_TO_CHAR_VAR_USE_IFs

! USE Interface statements for all subroutines called by SUBROUTINE WRT_REAL_TO_CHAR_VAR
! No subrs CALL'd by SUBROUTINE WRT_REAL_TO_CHAR_VAR

      END MODULE WRT_REAL_TO_CHAR_VAR_USE_IFs
